name: CI

on: 
  push:
    branches:
    - master
  schedule:
  - cron: "0 8 * * 1-5"

jobs:
  build:

    runs-on: macos-latest
    env:
      KATALON_BUNDLE_CLASSES: katalon_classes
      JACOCO_REPORT_DIR: jacoco_report
      JACOCO_LIB_DIR: tools/jacoco/lib

    steps:
    - name: Check out
      uses: actions/checkout@v1
      
    - name: Set up
      run: |
        mkdir $KATALON_BUNDLE_CLASSES
        mkdir $JACOCO_REPORT_DIR
        brew install coreutils
      
    - name: Download KRE
      run: |
        curl -o "katalon_runtime_engine.tar.gz" "$KRE_DOWNLOAD_LINK"
        tar -xzvf katalon_runtime_engine.tar.gz
        rm katalon_runtime_engine.tar.gz
      env:
        KRE_DOWNLOAD_LINK: https://download.katalon.com/7.2.1/Katalon_Studio_Engine_MacOS-7.2.1.tar.gz
        
    - name: Extract Katalon bundle jar files
      run: |
        export JAR_DIR=$(realpath "Katalon_Studio_Engine_MacOS-7.2.1/Katalon Studio Engine.app/Contents/Eclipse/plugins")
        export OUTPUT_DIR=$(realpath $KATALON_BUNDLE_CLASSES)   
        ./tools/extract-katalon-bundles.sh "$JAR_DIR" "$OUTPUT_DIR"
        
    - name: Inject Jacoco agent for execution
      run: |
        export SETTINGS_DIR=$(realpath settings/internal)
        export REPORT_FILE=$(realpath $JACOCO_REPORT_DIR/jacoco.exec)
        export JACOCOAGENT=$(realpath $JACOCO_LIB_DIR/jacocoagent.jar)
        ./tools/inject-jacocoagent.sh "$SETTINGS_DIR" "$JACOCOAGENT" "$REPORT_FILE"
        
    - name: Execute tests
      run: |
        export PROJECT_PATH=$(realpath web-samples.prj)
        cd "Katalon_Studio_Engine_MacOS-7.2.1/Katalon Studio Engine.app/Contents/MacOS"
        ./katalonc -noSplash -runMode=console -projectPath="$PROJECT_PATH" -retry=0 -testSuitePath="Test Suites/WebUI Builtin Keywords Test" -executionProfile="default" -browserType="Chrome" -apiKey="0d954e41-886c-4532-b12f-b04a06f84ff0"
        
        
         
         
         
      
