name: CI

on: 
  push:
    branches:
    - master
  schedule:
  - cron: "0 8 * * 1-5"

jobs:
  build:

    runs-on: macos-latest
    env:
      KATALON_BUNDLE_CLASSES: katalon_classes
      JACOCO_REPORT_DIR: jacoco_report
      JACOCO_LIB_DIR: tools/jacoco/lib

    steps:
    - name: Check out
      uses: actions/checkout@v1
      
    - name: Setup Java
      uses: actions/setup-java@master
      with:
        java-version: 1.8
        java-package: jre
      
    - name: Install coreutils
      run:
        brew install coreutils
      
    - name: Create common directories
      run: |
        mkdir $KATALON_BUNDLE_CLASSES
        mkdir $JACOCO_REPORT_DIR
              
    - name: Download KRE
      run: |
        curl "$KRE_DOWNLOAD_LINK" -o "katalon_runtime_engine.tar.gz" -L 
        tar -xzvf katalon_runtime_engine.tar.gz
        rm katalon_runtime_engine.tar.gz
      env:
        KRE_DOWNLOAD_LINK: https://github.com/katalon-studio/katalon-studio/releases/download/v7.2.3/Katalon_Studio_Engine_MacOS-7.2.3.tar.gz
        
    - name: Extract Katalon bundle jar files
      run: |
        export JAR_DIR=$(realpath "Katalon_Studio_Engine_MacOS-7.2.3/Katalon Studio Engine.app/Contents/Eclipse/plugins")
        export OUTPUT_DIR=$(realpath $KATALON_BUNDLE_CLASSES)   
        ./tools/extract-katalon-bundles.sh "$JAR_DIR" "$OUTPUT_DIR"
        
    - name: Inject Jacoco agent for execution
      run: |
        export SETTINGS_DIR=$(realpath settings/internal)
        export REPORT_FILE=$(realpath $JACOCO_REPORT_DIR/jacoco.exec)
        export JACOCOAGENT=$(realpath $JACOCO_LIB_DIR/jacocoagent.jar)
        touch $REPORT_FILE
        ./tools/inject-jacocoagent.sh "$SETTINGS_DIR" "$JACOCOAGENT" "$REPORT_FILE"
        cat $SETTINGS_DIR/com.kms.katalon.execution.setting.properties
        
    - name: Execute tests
      run: |
        export PROJECT_PATH=$(realpath web-samples.prj)
        cd "Katalon_Studio_Engine_MacOS-7.2.3/Katalon Studio Engine.app/Contents/MacOS"
        ./katalonc -noSplash -runMode=console -projectPath="$PROJECT_PATH" -retry=0 -testSuitePath="Test Suites/WebUI Builtin Keywords Test" -executionProfile="default" -browserType="Chrome" -apiKey="${{ secrets.KRE_API_KEY }}"
        
    - name: Generate XML coverage report
      run: |
        export JACOCO_EXEC_FILE=$(realpath $JACOCO_REPORT_DIR/jacoco.exec)
        export XML_REPORT_FILE=$(realpath $JACOCO_REPORT_DIR/jacoco.xml)
        export JACOCOCLI=$JACOCO_LIB_DIR/jacococli.jar
        touch $XML_REPORT_FILE
        java -jar $JACOCOCLI report $JACOCO_EXEC_FILE --classfiles $KATALON_BUNDLE_CLASSES --xml $XML_REPORT_FILE
         
      
