name: CI

on: 
  push:
    branches:
    - master
  schedule:
  - cron: "0 8 * * 1-5"

jobs:
  build:

    runs-on: macos-latest
    env:
      KATALON_BUNDLE_CLASSES: katalon_classes

    steps:
    - name: Check out
      uses: actions/checkout@v1
      
    - name: Download KRE
      run: |
        curl -o "katalon.tar.gz" "$KRE_DOWNLOAD_LINK"
        tar -xzvf katalon.tar.gz
        rm katalon.tar.gz
      env:
        KRE_DOWNLOAD_LINK: https://download.katalon.com/7.2.1/Katalon_Studio_Engine_MacOS-7.2.1.tar.gz

    - name: Extract Katalon bundle jar files
      run: |
        mkdir $KATALON_BUNDLE_CLASSES
        ./tools/extract-katalon-bundles.sh "$JAR_DIR" "$EXTRACT_DIR"
      env:
        JAR_DIR: Katalon_Studio_Engine_Windows_64-7.2.1/Contents/Eclipse/plugins     
      
